// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

type AnalyzeCldTextResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeCldTextResponse *components.AnalyzeCldTextResponse
	// Analysis accepted
	AsyncOperationAcceptedResponse *components.AsyncOperationAcceptedResponse
}

func (o *AnalyzeCldTextResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeCldTextResponse) GetAnalyzeCldTextResponse() *components.AnalyzeCldTextResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeCldTextResponse
}

func (o *AnalyzeCldTextResponse) GetAsyncOperationAcceptedResponse() *components.AsyncOperationAcceptedResponse {
	if o == nil {
		return nil
	}
	return o.AsyncOperationAcceptedResponse
}
