// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

type AnalyzeImageQualityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeImageQualityResponse *components.AnalyzeImageQualityResponse
	// Analysis accepted
	AsyncOperationAcceptedResponse *components.AsyncOperationAcceptedResponse
}

func (o *AnalyzeImageQualityResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeImageQualityResponse) GetAnalyzeImageQualityResponse() *components.AnalyzeImageQualityResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeImageQualityResponse
}

func (o *AnalyzeImageQualityResponse) GetAsyncOperationAcceptedResponse() *components.AsyncOperationAcceptedResponse {
	if o == nil {
		return nil
	}
	return o.AsyncOperationAcceptedResponse
}
