// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeAIVisionTaggingResponseData struct {
	Entity   *string                      `json:"entity,omitempty"`
	Analysis *AIVisionTaggingAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeAIVisionTaggingResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeAIVisionTaggingResponseData) GetAnalysis() *AIVisionTaggingAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeAIVisionTaggingResponse struct {
	Limits    *LimitsObject                       `json:"limits,omitempty"`
	RequestID *string                             `json:"request_id,omitempty"`
	Data      *AnalyzeAIVisionTaggingResponseData `json:"data,omitempty"`
}

func (o *AnalyzeAIVisionTaggingResponse) GetLimits() *LimitsObject {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeAIVisionTaggingResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AnalyzeAIVisionTaggingResponse) GetData() *AnalyzeAIVisionTaggingResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}
