// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeGoogleLogoDetectionResponseData struct {
	Entity   *string                          `json:"entity,omitempty"`
	Analysis *GoogleLogoDetectionAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeGoogleLogoDetectionResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeGoogleLogoDetectionResponseData) GetAnalysis() *GoogleLogoDetectionAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeGoogleLogoDetectionResponse struct {
	Limits    *LimitsObject                           `json:"limits,omitempty"`
	RequestID *string                                 `json:"request_id,omitempty"`
	Data      *AnalyzeGoogleLogoDetectionResponseData `json:"data,omitempty"`
}

func (o *AnalyzeGoogleLogoDetectionResponse) GetLimits() *LimitsObject {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeGoogleLogoDetectionResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AnalyzeGoogleLogoDetectionResponse) GetData() *AnalyzeGoogleLogoDetectionResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}
