// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type TagDefinitions struct {
	// The name of the tag to apply. This can be any string and does not affect the decision process
	Name string `json:"name"`
	// A description to be used by the AI to determine whether the tag should be applied
	Description string `json:"description"`
}

func (o *TagDefinitions) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *TagDefinitions) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

type AnalyzeAIVisionTaggingRequest struct {
	Source Source `json:"source"`
	// Whether to perform the analysis asynchronously.
	// If true, the response is returned immediately and analysis is done in the background.
	// Once complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.
	Async *bool `json:"async,omitempty"`
	// The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.
	NotificationURL *string          `json:"notification_url,omitempty"`
	TagDefinitions  []TagDefinitions `json:"tag_definitions"`
}

func (o *AnalyzeAIVisionTaggingRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}

func (o *AnalyzeAIVisionTaggingRequest) GetAsync() *bool {
	if o == nil {
		return nil
	}
	return o.Async
}

func (o *AnalyzeAIVisionTaggingRequest) GetNotificationURL() *string {
	if o == nil {
		return nil
	}
	return o.NotificationURL
}

func (o *AnalyzeAIVisionTaggingRequest) GetTagDefinitions() []TagDefinitions {
	if o == nil {
		return []TagDefinitions{}
	}
	return o.TagDefinitions
}
