// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeAIVisionModerationRequest struct {
	Source Source `json:"source"`
	// Whether to perform the analysis asynchronously.
	// If true, the response is returned immediately and analysis is done in the background.
	// Once complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.
	Async *bool `json:"async,omitempty"`
	// The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.
	NotificationURL *string `json:"notification_url,omitempty"`
	// A list of yes/no questions
	RejectionQuestions []string `json:"rejection_questions,omitempty"`
}

func (o *AnalyzeAIVisionModerationRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}

func (o *AnalyzeAIVisionModerationRequest) GetAsync() *bool {
	if o == nil {
		return nil
	}
	return o.Async
}

func (o *AnalyzeAIVisionModerationRequest) GetNotificationURL() *string {
	if o == nil {
		return nil
	}
	return o.NotificationURL
}

func (o *AnalyzeAIVisionModerationRequest) GetRejectionQuestions() []string {
	if o == nil {
		return nil
	}
	return o.RejectionQuestions
}
