// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeWatermarkDetectionResponseData struct {
	Entity   *string                         `json:"entity,omitempty"`
	Analysis *WatermarkDetectionAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeWatermarkDetectionResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeWatermarkDetectionResponseData) GetAnalysis() *WatermarkDetectionAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeWatermarkDetectionResponse struct {
	Limits    *LimitsObject                          `json:"limits,omitempty"`
	RequestID *string                                `json:"request_id,omitempty"`
	Data      *AnalyzeWatermarkDetectionResponseData `json:"data,omitempty"`
}

func (o *AnalyzeWatermarkDetectionResponse) GetLimits() *LimitsObject {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeWatermarkDetectionResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AnalyzeWatermarkDetectionResponse) GetData() *AnalyzeWatermarkDetectionResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}
