// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeCaptioningResponseData struct {
	Entity   *string                 `json:"entity,omitempty"`
	Analysis *CaptioningAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeCaptioningResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeCaptioningResponseData) GetAnalysis() *CaptioningAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeCaptioningResponse struct {
	Limits    *LimitsObject                  `json:"limits,omitempty"`
	RequestID *string                        `json:"request_id,omitempty"`
	Data      *AnalyzeCaptioningResponseData `json:"data,omitempty"`
}

func (o *AnalyzeCaptioningResponse) GetLimits() *LimitsObject {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeCaptioningResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AnalyzeCaptioningResponse) GetData() *AnalyzeCaptioningResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}
