// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AnalyzeImageQualityResponseData struct {
	Entity   *string                   `json:"entity,omitempty"`
	Analysis *ImageQualityAnalysisData `json:"analysis,omitempty"`
}

func (o *AnalyzeImageQualityResponseData) GetEntity() *string {
	if o == nil {
		return nil
	}
	return o.Entity
}

func (o *AnalyzeImageQualityResponseData) GetAnalysis() *ImageQualityAnalysisData {
	if o == nil {
		return nil
	}
	return o.Analysis
}

type AnalyzeImageQualityResponse struct {
	Limits    *LimitsObject                    `json:"limits,omitempty"`
	RequestID *string                          `json:"request_id,omitempty"`
	Data      *AnalyzeImageQualityResponseData `json:"data,omitempty"`
}

func (o *AnalyzeImageQualityResponse) GetLimits() *LimitsObject {
	if o == nil {
		return nil
	}
	return o.Limits
}

func (o *AnalyzeImageQualityResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}

func (o *AnalyzeImageQualityResponse) GetData() *AnalyzeImageQualityResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}
