// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type BaseAnalyzeRequest struct {
	Source Source `json:"source"`
	// Whether to perform the analysis asynchronously.
	// If true, the response is returned immediately and analysis is done in the background.
	// Once complete, a webhook notification will be sent to the specified URL and/or to the URLs defined in the Webhook Notifications settings of your Cloudinary Console.
	Async *bool `json:"async,omitempty"`
	// The webhook URL to notify when the analysis is complete. Only relevant when async is set to true.
	NotificationURL *string `json:"notification_url,omitempty"`
}

func (o *BaseAnalyzeRequest) GetSource() Source {
	if o == nil {
		return Source{}
	}
	return o.Source
}

func (o *BaseAnalyzeRequest) GetAsync() *bool {
	if o == nil {
		return nil
	}
	return o.Async
}

func (o *BaseAnalyzeRequest) GetNotificationURL() *string {
	if o == nil {
		return nil
	}
	return o.NotificationURL
}
