// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Details struct {
}

type ErrorObject struct {
	Category  *ErrorCategory `json:"category,omitempty"`
	Code      *string        `json:"code,omitempty"`
	Message   *string        `json:"message,omitempty"`
	Details   *Details       `json:"details,omitempty"`
	RequestID *string        `json:"request_id,omitempty"`
}

func (o *ErrorObject) GetCategory() *ErrorCategory {
	if o == nil {
		return nil
	}
	return o.Category
}

func (o *ErrorObject) GetCode() *string {
	if o == nil {
		return nil
	}
	return o.Code
}

func (o *ErrorObject) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *ErrorObject) GetDetails() *Details {
	if o == nil {
		return nil
	}
	return o.Details
}

func (o *ErrorObject) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
