// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type SchemeCloudinaryAuth struct {
	APIKey    string `json:"api_key" security:"name=api_key"`
	APISecret string `json:"api_secret" security:"name=api_secret"`
}

func (o *SchemeCloudinaryAuth) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *SchemeCloudinaryAuth) GetAPISecret() string {
	if o == nil {
		return ""
	}
	return o.APISecret
}
