// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Security struct {
	CloudinaryAuth *SchemeCloudinaryAuth `security:"scheme,type=http,subtype=custom"`
	OAuth2         *string               `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *Security) GetCloudinaryAuth() *SchemeCloudinaryAuth {
	if o == nil {
		return nil
	}
	return o.CloudinaryAuth
}

func (o *Security) GetOAuth2() *string {
	if o == nil {
		return nil
	}
	return o.OAuth2
}
