// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

type ErrorCategory string

const (
	ErrorCategoryUserError      ErrorCategory = "user_error"
	ErrorCategoryAuthError      ErrorCategory = "auth_error"
	ErrorCategoryServerError    ErrorCategory = "server_error"
	ErrorCategoryRateLimitError ErrorCategory = "rate_limit_error"
)

func (e ErrorCategory) ToPointer() *ErrorCategory {
	return &e
}
func (e *ErrorCategory) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user_error":
		fallthrough
	case "auth_error":
		fallthrough
	case "server_error":
		fallthrough
	case "rate_limit_error":
		*e = ErrorCategory(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ErrorCategory: %v", v)
	}
}
