// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Vertices struct {
	X *int64 `json:"x,omitempty"`
	Y *int64 `json:"y,omitempty"`
}

func (o *Vertices) GetX() *int64 {
	if o == nil {
		return nil
	}
	return o.X
}

func (o *Vertices) GetY() *int64 {
	if o == nil {
		return nil
	}
	return o.Y
}

type BoundingPoly struct {
	Vertices []Vertices `json:"vertices,omitempty"`
}

func (o *BoundingPoly) GetVertices() []Vertices {
	if o == nil {
		return nil
	}
	return o.Vertices
}

type LogoAnnotations struct {
	Mid          *string      `json:"mid,omitempty"`
	Description  string       `json:"description"`
	Score        float64      `json:"score"`
	BoundingPoly BoundingPoly `json:"bounding_poly"`
}

func (o *LogoAnnotations) GetMid() *string {
	if o == nil {
		return nil
	}
	return o.Mid
}

func (o *LogoAnnotations) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *LogoAnnotations) GetScore() float64 {
	if o == nil {
		return 0.0
	}
	return o.Score
}

func (o *LogoAnnotations) GetBoundingPoly() BoundingPoly {
	if o == nil {
		return BoundingPoly{}
	}
	return o.BoundingPoly
}

type GoogleLogoDetectionAnalysisData struct {
	LogoAnnotations []LogoAnnotations `json:"logo_annotations"`
}

func (o *GoogleLogoDetectionAnalysisData) GetLogoAnnotations() []LogoAnnotations {
	if o == nil {
		return []LogoAnnotations{}
	}
	return o.LogoAnnotations
}
