// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type AsyncOperationAcceptedResponseData struct {
	TaskID string `json:"task_id"`
	// The status of an async task
	Status TaskStatus `json:"status"`
}

func (o *AsyncOperationAcceptedResponseData) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

func (o *AsyncOperationAcceptedResponseData) GetStatus() TaskStatus {
	if o == nil {
		return TaskStatus("")
	}
	return o.Status
}

// AsyncOperationAcceptedResponse - Analysis accepted
type AsyncOperationAcceptedResponse struct {
	Data      *AsyncOperationAcceptedResponseData `json:"data,omitempty"`
	RequestID *string                             `json:"request_id,omitempty"`
}

func (o *AsyncOperationAcceptedResponse) GetData() *AsyncOperationAcceptedResponseData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *AsyncOperationAcceptedResponse) GetRequestID() *string {
	if o == nil {
		return nil
	}
	return o.RequestID
}
