// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Detections struct {
	Name       string  `json:"name"`
	Confidence float64 `json:"confidence"`
}

func (o *Detections) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Detections) GetConfidence() float64 {
	if o == nil {
		return 0.0
	}
	return o.Confidence
}

type WatermarkDetectionAnalysisData struct {
	Detections   []Detections `json:"detections,omitempty"`
	ModelVersion *int64       `json:"model_version,omitempty"`
}

func (o *WatermarkDetectionAnalysisData) GetDetections() []Detections {
	if o == nil {
		return nil
	}
	return o.Detections
}

func (o *WatermarkDetectionAnalysisData) GetModelVersion() *int64 {
	if o == nil {
		return nil
	}
	return o.ModelVersion
}
