// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

type AnalyzeGoogleLogoDetectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeGoogleLogoDetectionResponse *components.AnalyzeGoogleLogoDetectionResponse
}

func (o *AnalyzeGoogleLogoDetectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeGoogleLogoDetectionResponse) GetAnalyzeGoogleLogoDetectionResponse() *components.AnalyzeGoogleLogoDetectionResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeGoogleLogoDetectionResponse
}
