// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

// RateLimitedResponse - Rate limited
type RateLimitedResponse struct {
	Error_ *components.ErrorObject  `json:"error,omitempty"`
	Limits *components.LimitsObject `json:"limits,omitempty"`
}

var _ error = &RateLimitedResponse{}

func (e *RateLimitedResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
