// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

// ErrorResponse - Bad request
type ErrorResponse struct {
	Error_ *components.ErrorObject `json:"error,omitempty"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
