// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

type AnalyzeGoogleTaggingResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeGoogleTaggingResponse *components.AnalyzeGoogleTaggingResponse
	// Analysis accepted
	AsyncOperationAcceptedResponse *components.AsyncOperationAcceptedResponse
}

func (o *AnalyzeGoogleTaggingResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeGoogleTaggingResponse) GetAnalyzeGoogleTaggingResponse() *components.AnalyzeGoogleTaggingResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeGoogleTaggingResponse
}

func (o *AnalyzeGoogleTaggingResponse) GetAsyncOperationAcceptedResponse() *components.AsyncOperationAcceptedResponse {
	if o == nil {
		return nil
	}
	return o.AsyncOperationAcceptedResponse
}
