// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

type AnalyzeWatermarkDetectionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis succeeded
	AnalyzeWatermarkDetectionResponse *components.AnalyzeWatermarkDetectionResponse
	// Analysis accepted
	AsyncOperationAcceptedResponse *components.AsyncOperationAcceptedResponse
}

func (o *AnalyzeWatermarkDetectionResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *AnalyzeWatermarkDetectionResponse) GetAnalyzeWatermarkDetectionResponse() *components.AnalyzeWatermarkDetectionResponse {
	if o == nil {
		return nil
	}
	return o.AnalyzeWatermarkDetectionResponse
}

func (o *AnalyzeWatermarkDetectionResponse) GetAsyncOperationAcceptedResponse() *components.AsyncOperationAcceptedResponse {
	if o == nil {
		return nil
	}
	return o.AsyncOperationAcceptedResponse
}
