// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/cloudinary/analysis-go/cloudinaryanalysis/models/components"
)

type GetAnalysisTaskStatusRequest struct {
	// The ID of the analysis task
	TaskID string `pathParam:"style=simple,explode=false,name=task_id"`
}

func (o *GetAnalysisTaskStatusRequest) GetTaskID() string {
	if o == nil {
		return ""
	}
	return o.TaskID
}

type GetAnalysisTaskStatusResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Analysis task status
	GetTaskStatusResponse *components.GetTaskStatusResponse
}

func (o *GetAnalysisTaskStatusResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetAnalysisTaskStatusResponse) GetGetTaskStatusResponse() *components.GetTaskStatusResponse {
	if o == nil {
		return nil
	}
	return o.GetTaskStatusResponse
}
